// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2eXTT1Lif-W3q43qHQmFA0LAzTq7xjeI',
    appId: '1:598440548492:web:3ccf09bf120ec6dd0b43a9',
    messagingSenderId: '598440548492',
    projectId: 'casa-verao-2023',
    authDomain: 'casa-verao-2023.firebaseapp.com',
    databaseURL: 'https://casa-verao-2023-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'casa-verao-2023.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9xcD7Ton9VP2lq6XqNExn6VMVo3VP97Q',
    appId: '1:598440548492:android:cbe3e327d493392f0b43a9',
    messagingSenderId: '598440548492',
    projectId: 'casa-verao-2023',
    databaseURL: 'https://casa-verao-2023-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'casa-verao-2023.appspot.com',
  );
}
